#!/usr/bin/env python3
"""
gen_font8x8.py - Turn the public-domain font8x8 header into a C table for
the Suite's RIPscrip default (font 0) bitmap glyphs.

Part of the Montreal Greek Times Unicorn Suite.
Copyright (C) 2026 Dimitri Papadopoulos and The Montreal Greek Times
Licensed under the GNU Affero General Public License v3.0 or later.

Source glyphs: font8x8 by Daniel Hepper, released to the public domain,
based on the public-domain 8x8 VGA font by Marcel Sondaas. See
THIRD-PARTY-NOTICES.md.

  usage: python tools/gen_font8x8.py <font8x8_basic.h> > src/rip_font8x8_data.c

In the source each glyph is eight bytes, one per scan line, and within a
byte bit 0 is the leftmost pixel. That layout is preserved here, so the
renderer tests bit (x & 7).
"""

import re
import sys


def main():
    if len(sys.argv) < 2:
        sys.stderr.write("usage: gen_font8x8.py <font8x8_basic.h>\n")
        return 2
    with open(sys.argv[1], "r", encoding="latin-1") as f:
        text = f.read()

    # Each glyph is a brace group of eight 0x.. bytes.
    groups = re.findall(r"\{([^{}]*0[xX][0-9A-Fa-f]{2}[^{}]*)\}", text)
    glyphs = []
    for g in groups:
        vals = re.findall(r"0[xX]([0-9A-Fa-f]{2})", g)
        if len(vals) == 8:
            glyphs.append([int(v, 16) for v in vals])
    if len(glyphs) < 128:
        sys.stderr.write("parsed only %d glyphs, expected 128\n" % len(glyphs))
        return 1
    glyphs = glyphs[:128]

    out = []
    w = out.append
    w("/*")
    w(" * rip_font8x8_data.c - 8x8 bitmap glyphs for RIPscrip font 0.")
    w(" *                     GENERATED, do not edit.")
    w(" *")
    w(" * Generated by tools/gen_font8x8.py from font8x8 by Daniel Hepper,")
    w(" * released to the public domain, itself based on the public-domain")
    w(" * 8x8 VGA font by Marcel Sondaas. See THIRD-PARTY-NOTICES.md.")
    w(" *")
    w(" * Eight bytes per glyph, one per scan line, bit 0 leftmost.")
    w(" *")
    w(" * Part of the Montreal Greek Times Unicorn Suite.")
    w(" * Copyright (C) 2026 Dimitri Papadopoulos and The Montreal Greek Times")
    w(" * Licensed under the GNU Affero General Public License v3.0 or later.")
    w(" * See /COPYING and THIRD-PARTY-NOTICES.md.")
    w(" */")
    w("")
    w('#include "rip_font8x8.h"')
    w("")
    w("const unsigned char rip_font8x8[128][8] = {")
    for i, g in enumerate(glyphs):
        ch = chr(i) if 32 <= i < 127 else ""
        label = (" /* %s */" % ch) if ch and ch != "*" and ch != "/" else ""
        w("    { %s },%s" % (", ".join("0x%02X" % b for b in g), label))
    w("};")
    w("")

    sys.stdout.write("\n".join(out) + "\n")
    sys.stderr.write("emitted %d glyphs\n" % len(glyphs))
    return 0


if __name__ == "__main__":
    sys.exit(main())
