#!/usr/bin/env python3
"""
gen_hershey.py - Turn public-domain Hershey .jhf font data into a compact
C table for the Suite's RIPscrip stroked-font renderer.

Part of the Montreal Greek Times Unicorn Suite.
Copyright (C) 2026 Dimitri Papadopoulos and The Montreal Greek Times
Licensed under the GNU Affero General Public License v3.0 or later.

The Hershey fonts themselves are public domain. See THIRD-PARTY-NOTICES.md
for the acknowledgements the distribution requires.

  usage: python tools/gen_hershey.py <jhf-dir> > src/rip_hershey_data.c

.jhf format: for each glyph, 5 characters of glyph number, 3 characters of
vertex count, then that many coordinate pairs. Each coordinate character is
its ASCII value minus 'R'. The first pair is not a vertex: it is the left
and right hand position, which gives the advance width. A " R" pair is a
pen-up move. Records may wrap across physical lines, so the file is read as
one character stream with newlines skipped.

Glyphs are stored in the file in ASCII order beginning at space (0x20).
"""

import sys
import os

# RIP font number -> (Hershey file, human name). RIP 0 is the bitmap font
# and is not in this table.
FONTS = [
    (1,  "rowmant", "Triplex"),
    (2,  "rowmans", "Small"),
    (3,  "futural", "Sans Serif"),
    (4,  "gothgbt", "Gothic"),
    (5,  "scripts", "Script"),
    (6,  "rowmans", "Simplex"),
    (7,  "scriptc", "Triplex Script"),
    (8,  "rowmand", "Complex"),
    (9,  "futuram", "European"),
    (10, "timesrb", "Bold"),
]

FIRST_CHAR = 0x20
LAST_CHAR = 0x7E


def read_glyphs(path):
    """Parse a .jhf file into a list of (left, right, strokes)."""
    with open(path, "r", encoding="latin-1") as f:
        data = f.read()
    # One character stream: newlines are formatting, not data.
    s = data.replace("\r", "").replace("\n", "")
    glyphs = []
    i = 0
    n = len(s)
    while i + 8 <= n:
        # 5 chars glyph number (right justified, may hold spaces), 3 chars count
        count_field = s[i + 5:i + 8]
        try:
            count = int(count_field)
        except ValueError:
            break
        i += 8
        need = count * 2
        if i + need > n:
            break
        body = s[i:i + need]
        i += need

        left = ord(body[0]) - ord('R')
        right = ord(body[1]) - ord('R')
        strokes = []
        cur = []
        for k in range(1, count):
            a = body[k * 2]
            b = body[k * 2 + 1]
            if a == ' ' and b == 'R':
                if len(cur) >= 1:
                    strokes.append(cur)
                cur = []
                continue
            cur.append((ord(a) - ord('R'), ord(b) - ord('R')))
        if len(cur) >= 1:
            strokes.append(cur)
        glyphs.append((left, right, strokes))
    return glyphs


def main():
    if len(sys.argv) < 2:
        sys.stderr.write("usage: gen_hershey.py <jhf-dir>\n")
        return 2
    d = sys.argv[1]

    cache = {}
    for _num, fname, _name in FONTS:
        if fname not in cache:
            cache[fname] = read_glyphs(os.path.join(d, fname + ".jhf"))

    out = []
    w = out.append

    w("/*")
    w(" * rip_hershey_data.c - Hershey stroke glyph data for the RIPscrip")
    w(" *                     stroked fonts. GENERATED, do not edit.")
    w(" *")
    w(" * Generated by tools/gen_hershey.py from the public-domain Hershey")
    w(" * font distribution. The Hershey Fonts were originally created by")
    w(" * Dr. A. V. Hershey while working at the U. S. National Bureau of")
    w(" * Standards. The format of the font data in that distribution was")
    w(" * originally created by James Hurt, Cognition Inc.")
    w(" *")
    w(" * Part of the Montreal Greek Times Unicorn Suite.")
    w(" * Copyright (C) 2026 Dimitri Papadopoulos and The Montreal Greek Times")
    w(" * Licensed under the GNU Affero General Public License v3.0 or later.")
    w(" * See /COPYING and THIRD-PARTY-NOTICES.md.")
    w(" */")
    w("")
    w('#include "rip_hershey.h"')
    w("")

    # Emit one point pool and one glyph table per distinct Hershey face.
    face_order = []
    for _num, fname, _name in FONTS:
        if fname not in face_order:
            face_order.append(fname)

    for fname in face_order:
        glyphs = cache[fname]
        pts = []
        recs = []
        for code in range(FIRST_CHAR, LAST_CHAR + 1):
            gi = code - FIRST_CHAR
            if gi >= len(glyphs):
                recs.append((0, 0, 0, 0))
                continue
            left, right, strokes = glyphs[gi]
            start = len(pts)
            npt = 0
            for st in strokes:
                # Pen-up marker: a point with x == RIP_HERSHEY_PENUP.
                pts.append((-128, -128))
                npt += 1
                for (x, y) in st:
                    xx = max(-127, min(127, x))
                    yy = max(-127, min(127, y))
                    pts.append((xx, yy))
                    npt += 1
            recs.append((left, right, start, npt))

        w("static const signed char PTS_%s[] = {" % fname.upper())
        line = "   "
        for (x, y) in pts:
            item = " %d,%d," % (x, y)
            if len(line) + len(item) > 76:
                w(line)
                line = "   "
            line += item
        if line.strip():
            w(line)
        w("};")
        w("")
        w("static const RipHersheyGlyph GLYPHS_%s[] = {" % fname.upper())
        for (left, right, start, npt) in recs:
            w("    { %d, %d, %d, %d }," % (left, right, start, npt))
        w("};")
        w("")

    w("const RipHersheyFace rip_hershey_faces[RIP_HERSHEY_FACE_COUNT] = {")
    for fname in face_order:
        w('    { "%s", GLYPHS_%s, PTS_%s },' % (fname, fname.upper(), fname.upper()))
    w("};")
    w("")
    w("/* RIP font number (1-10) -> index into rip_hershey_faces. */")
    w("const unsigned char rip_hershey_font_map[11] = {")
    w("    0,  /* 0: bitmap font, not a stroked face */")
    for num, fname, name in FONTS:
        w("    %d,  /* %d: %s (%s) */" % (face_order.index(fname), num, name, fname))
    w("};")
    w("")

    sys.stdout.write("\n".join(out) + "\n")

    # Diagnostics to stderr: the natural cap height of each face, measured
    # from 'H', which is what the renderer scales against.
    sys.stderr.write("face      H-top  H-base  capheight  advance('H')\n")
    for fname in face_order:
        glyphs = cache[fname]
        g = glyphs[ord('H') - FIRST_CHAR]
        ys = [p[1] for st in g[2] for p in st]
        sys.stderr.write("%-9s %5d  %6d  %9d  %d\n" %
                         (fname, min(ys), max(ys), max(ys) - min(ys),
                          g[1] - g[0]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
