/*
 * rip_font8x8.h - 8x8 bitmap glyphs for RIPscrip font 0.
 *
 * Part of the Montreal Greek Times Unicorn Suite.
 * Copyright (C) 2026 Dimitri Papadopoulos and The Montreal Greek Times
 * This file is part of the MGT Unicorn Suite.
 * Licensed under the GNU Affero General Public License v3.0 or later.
 * See /COPYING for the full license text.
 *
 * Glyph data is generated by tools/gen_font8x8.py from font8x8 by Daniel
 * Hepper (public domain), based on the public-domain 8x8 VGA font by
 * Marcel Sondaas. See THIRD-PARTY-NOTICES.md.
 *
 * Eight bytes per glyph, one per scan line, bit 0 leftmost.
 */

#ifndef RIP_FONT8X8_H_INCLUDED
#define RIP_FONT8X8_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char rip_font8x8[128][8];

#ifdef __cplusplus
}
#endif

#endif /* RIP_FONT8X8_H_INCLUDED */
